# Generated by Django 3.2.8 on 2022-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0003_rename_movies_actor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
