# Generated by Django 3.2.8 on 2022-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0004_alter_actor_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
